---
# Automated release playbook for Ansible Collections.
# originally created by geerlingguy
# https://github.com/geerlingguy/ansible-collection-mac/blob/master/galaxy-deploy.yml
#
# Originally based on Ericsysmin's 2020 blog post. Meant to be used in a GitHub
# Actions CI environment.
#
# Requires a ANSIBLE_GALAXY_TOKEN secret to be configured on the GitHub repo.
#
# Usage:
#   ansible-playbook -i 'localhost,' galaxy-deploy.yml \
#   -e "github_tag=${{ github.ref }}"

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    namespace: jhollowe
    collection: cloudlab
    # Requires github_tag to be set when calling playbook.
    release_tag: "{{ github_tag.split('/')[-1] }}"

  pre_tasks:
    - name: Ensure ANSIBLE_GALAXY_TOKEN is set.
      fail:
        msg: A valid ANSIBLE_GALAXY_TOKEN must be set.
      when: "lookup('env','ANSIBLE_GALAXY_TOKEN') | length == 0"

    - name: Ensure the ~/.ansible directory exists.
      file:
        path: ~/.ansible
        state: directory
        mode: 0700

    - name: Write the Galaxy token to ~/.ansible/galaxy_token
      copy:
        content: |
          token: {{ lookup('env','ANSIBLE_GALAXY_TOKEN') }}
        dest: ~/.ansible/galaxy_token
        mode: 0600

  tasks:
    - name: Ensure the galaxy.yml tag is up to date.
      lineinfile:
        path: galaxy.yml
        regexp: "^version:"
        line: 'version: "{{ release_tag }}"'

    - name: Build the collection.
      command:
        cmd: ansible-galaxy collection build --force
        creates: ./{{ namespace }}-{{ collection }}-{{ release_tag }}.tar.gz


    - name: Publish the collection.
      command: >
        ansible-galaxy collection publish ./{{ namespace }}-{{ collection }}-{{ release_tag }}.tar.gz
