# heavily based off of https://github.com/geerlingguy/ansible-collection-mac/blob/master/.github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}

    steps:
      - name: Pull Repo
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache PIP packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('galaxy.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Publish to Ansible Galaxy
        run: ansible-playbook -i 'localhost,' galaxy-deploy.yml -e "github_tag=${{ github.ref }}"
